# rules https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# example https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# example https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.jsonc

# Default state for all rules
default: true

# no-multiple-blanks
MD012: false

# Line length
MD013: false

# Multiple headings with the same content
MD024: false

# Fenced code blocks should have a language specified
MD040: false

# Dollar signs used before commands without showing output
MD014: false

# Inline HTML
MD033: false

# /no-trailing-spaces
MD009: false

# First line in a file should be a top-level heading
MD041: false
