apiVersion: v2
appVersion: v0.3.7-rc.8
description: the HwameiStor local storage
name: hwameistor
type: application
version: v0.3.7-rc.8
dependencies:
  - name: hwameistor
    version: "v0.3.7-rc.8"
    repository: "http://hwameistor.io/hwameistor"
